sudo: required
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=fake-news-api-server
    - ORG=g0vhk
language: generic
services:
  - docker

script:
    - docker build -t $ORG/$REPO:$COMMIT api

after_success:
    - export TAG='latest'
    - docker tag $ORG/$REPO:$COMMIT $ORG/$REPO:$TAG
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $ORG/$REPO
