# Generated by Django 2.1.7 on 2019-08-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='fakenews/image')),
            ],
        ),
        migrations.CreateModel(
            name='LinkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('image', 'Image'), ('link', 'Link')], max_length=128)),
                ('image_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.ImageReport')),
                ('link_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.LinkReport')),
            ],
        ),
    ]
