# Generated by Django 2.1.7 on 2019-08-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagereport',
            name='image_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
