# Generated by Django 2.1.7 on 2019-08-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190824_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkreport',
            name='image',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='linkreport',
            name='short_text',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='linkreport',
            name='text',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='linkreport',
            name='title',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
