# Generated by Django 2.1.7 on 2019-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagereport',
            name='description',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
